### ISSUE TITLE
npm install fails at libxmljs-mt@0.18.0

### ISSUE THREAD

**Issue by HagayRatzabi** [cirsfid-unibo/lime-server#9]
Hi guys!

After installing @ cloning the project, when I do 'npm install' it fails in libxmljs-mt@0.18.0
It has a bug in node libs, or here buy I didn't undersatnd what I supposed to do to fix it.

If any one can help, can can be useful.
Thanks!

This is how it looks like:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs-mt@0.18.0 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs-mt@0.18.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@obujor, my os is Win 10 Enterprise 64-bit OS x64-based processor, Intel Core i7-6700T CPU 2.80Ghz, Desktop... what more? 

I'm in govrement office(Justice Department) but even when install it in my private computer in open network, I get the same error..

**Comment by obujor** [comment]
Hi,
I think you need to install this package https://github.com/felixrieseberg/windows-build-tools
If it's still not working make sure you use it with node v.8.x.

In general lime-server is supposed to work in linux/ubuntu based server not in the desktop, for development reason it will work on Windows but not are features are tested in Windows environment.

**Comment by HagayRatzabi** [comment]
> In general lime-server is supposed to work in linux/ubuntu based server not in the desktop, for development reason it will work on Windows but not are features are tested in Windows environment.

Thanks @obujor ! 
Sorry for late response.
We will install linux/ubuntu server, and try again.

There is any specific demands? Linux/Ubuntu version? Memory required? Amount of cores?

**Comment by obujor** [comment]
No specific demands, it depends on how big is your use case. In general lime-server doesn't use much memory. Remember that in order to use LIME you have to install eXist db and mongodb, so bear in mind their requirements as well.

**Comment by HagayRatzabi** [comment]
> Hi,
> I think you need to install this package https://github.com/felixrieseberg/windows-build-tools
> If it's still not working make sure you use it with node v.8.x.

Obujor, 
Still in windows:
I install this package - still fail.
I downgarde to node v.8.9.0 - still fail.

maybe I need to downgarde this one also? -  _node-gyp -v v3.6.2._
because fail related to it..  -  _npm ERR! libxmljs-mt@0.18.0 install: `node-gyp rebuild`_

Copy the fail error message :
_$ npm update

/> libxmljs-mt@0.18.0 install D:\elaw_learning\LIME-2.1-build-2017-05-19\lime-server\node_modules\libxmljs-mt
/> node-gyp rebuild

D:\elaw_learning\LIME-2.1-build-2017-05-19\lime-server\node_modules\libxmljs-mt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
gyp ERR! stack     at emitNone (events.js:106:13)
gyp ERR! stack     at TLSSocket.emit (events.js:208:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:637:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\elaw_learning\LIME-2.1-build-2017-05-19\lime-server\node_modules\libxmljs-mt
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs-mt@0.18.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs-mt@0.18.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HagayRa\AppData\Roaming\npm-cache\_logs\2019-10-24T08_50_28_530Z-debug.log_

**Comment by obujor** [comment]
Hi,
I don't know, you can submit the issue directly in the libxmljs project, we're just using this library.
